import React from "react";
import Button from 'react-bootstrap/Button';
import Container from 'react-bootstrap/Container';
import Spinner from 'react-bootstrap/Spinner';
import isEmpty from 'lodash/isEmpty';

import NavigationBar from '../Navbar';
import styles from './SurveyPageView.module.css';
import ZapFullView from "../Baskets/ZapFullView";
import Baskets from '../../constants/Baskets';

const SurveyPageView = ({ ...props }) => {
    const { questionNumber, onAnswer, surveyList, reDoSurvey, surveyComplete,
        submitResults, isLoading, answer } = props;

    const surveyCompleted = () => (
        <>
            <NavigationBar />
            <div key={questionNumber} className={styles.containerPadding}>
                <Container>
                    {
                        surveyComplete ? (<>
                            <Button
                                variant="outline-light"
                                onClick={reDoSurvey}
                                className={styles.buttonspacing}
                                size="lg"
                            >
                                Start Over
                        </Button>
                            <Button
                                href="/zaps"
                                variant="outline-light"
                                size="lg"
                            >
                                Explore all Zaps
                        </Button>
                        </>) : (
                                <Button
                                    variant="outline-light"
                                    onClick={submitResults}
                                    className={styles.buttonspacing}
                                    size="lg"
                                >
                                    Get Results
                                </Button>)
                    }
                    {
                        isLoading ? (
                            <>
                                <br />
                                <Spinner animation="grow" variant="light" />
                                <Spinner animation="grow" variant="light" />
                                <Spinner animation="grow" variant="light" />
                                <Spinner animation="grow" variant="light" />
                                <Spinner animation="grow" variant="light" />
                            </>
                        ) : (generateResult())
                    }
                </Container>
            </div>
        </>
    );

    const questions = () => {
        const questions = surveyList.map(item => {
            return (
                <>
                <NavigationBar />
                <div key={questionNumber} className={styles.containerPadding}>
                    <Container key={questionNumber}>
                        {questionNumber === 1 ? (
                            <><h4 style={{ color: "white" }}>Answer a few multiple choice questions to see which Zap might fit your needs:</h4><br /></>
                        ) : null}
                        <h4 style={{ color: "white" }}>{item.question}</h4>
                        <h5 style={{ color: "white", fontSize: 15 }}>Question {questionNumber} out of 4</h5>
                        <ol type="A" style={{ color: "white" }}>
                            {item.options.map(option => {
                                return (
                                    <li key={option.value} className={styles.buttonspacing}>
                                        <Button variant="outline-light" size="lg" onClick={() => onAnswer(option.key)}>
                                            {option.value}
                                        </Button>
                                    </li>
                                );
                            })}
                        </ol>
                        <br />
                        <h5 style={{ color: "white", fontSize: 15 }}>DISCLOSURE: THIS IS NOT INVESTMENT ADVICE. DO NOT MAKE INVESTMENT DECISIONS SOLELY BASED ON</h5>
                        <h5 style={{ color: "white", fontSize: 15 }}>RESULTS GENERATED BY THIS TOOL. THIS PROJECT IS IN BETA. USE AT YOUR OWN DISCRETION.</h5>
                    </Container>
                </div>
                </>
            );
        });
        return questions[questionNumber - 1];
    };

    const generateResult = () => {
        return (
            isEmpty(answer) ? null : (
                <>
                <br /> < br />
                <h4 style={{ color: "white" }}>
                    Based on your investment profile, you might find this Zap useful: <br />
                </h4>
                    <ZapFullView
                        name={Baskets[answer].name}
                        components={Baskets[answer].components}
                        isOrderable={Baskets[answer].isOrderable}
                        description={Baskets[answer].description}
                    />
                </>
            )
        );
    }

    const questionaire = (questionNumber) => {
        return (
            <div
                className="hero-image"
                style={{
                    height: "1000px",
                    marginBottom: "100px"
                }}
            >
                <div className={styles.containerPadding} style={{ paddingTop: "150px" }}>
                    {surveyList.length >= questionNumber ? questions() : surveyCompleted()}
                </div>
            </div>
        );
    };

    return questionaire(questionNumber);
};

export default SurveyPageView;

